Repository HI-PETMILY/hiPetmily, pull requests merged in 2023-10, with the labels that each got.

#42 Feature/#4/header&footer
  src/main/resources/static/css/common/headerFooter.css
  src/main/resources/static/js/common/headerFooter.js
  src/main/resources/static/static_Image/common/add_user_bk.png
  src/main/resources/static/static_Image/common/add_user_bu.png
  src/main/resources/static/static_Image/common/admin_bk.png
  src/main/resources/static/static_Image/common/admin_bu.png
  src/main/resources/static/static_Image/common/login_bk.png
  src/main/resources/static/static_Image/common/login_bu.png
  src/main/resources/static/static_Image/common/logout_bk.png
  src/main/resources/static/static_Image/common/logout_bu.png
  src/main/resources/static/static_Image/common/logout_wh.png
  src/main/resources/static/static_Image/common/mypage_bk.png
  src/main/resources/static/static_Image/common/mypage_bu.png
  src/main/resources/static/static_Image/common/mypage_wh.png
  src/main/resources/templates/common/header_black.html
Labels: Fix, HTML & CSS

#44 Feature/#5/mainpage UI
  src/main/java/com/mypet/petmily/main/controller/MainController.java
  src/main/resources/static/css/common/headerFooter.css
  src/main/resources/static/css/main/main.css
  src/main/resources/static/css/main/mainPage.css
  src/main/resources/static/js/common/headerFooter.js
  src/main/resources/static/js/main/mainPage.js
  src/main/resources/static/static_Image/common/main/add_user_bk.png
  src/main/resources/static/static_Image/common/main/add_user_bl.png
  src/main/resources/static/static_Image/common/main/add_user_bu.png
  src/main/resources/static/static_Image/common/main/add_user_wh.png
  src/main/resources/static/static_Image/common/main/admin_bk.png
  src/main/resources/static/static_Image/common/main/admin_bl.png
  src/main/resources/static/static_Image/common/main/admin_bu.png
  src/main/resources/static/static_Image/common/main/admin_wh.png
  src/main/resources/static/static_Image/common/main/banner1.png
  src/main/resources/static/static_Image/common/main/banner2.png
  src/main/resources/static/static_Image/common/main/banner3.png
  src/main/resources/static/static_Image/common/main/easytouse.png
  src/main/resources/static/static_Image/common/main/favicon.ico
  src/main/resources/static/static_Image/common/main/log_white.png
  src/main/resources/static/static_Image/common/main/login_bk.png
  src/main/resources/static/static_Image/common/main/login_bl.png
  src/main/resources/static/static_Image/common/main/login_bu.png
  src/main/resources/static/static_Image/common/main/login_wh.png
  src/main/resources/static/static_Image/common/main/logo_black.png
  src/main/resources/static/static_Image/common/main/logout_bk.png
  src/main/resources/static/static_Image/common/main/logout_bl.png
  src/main/resources/static/static_Image/common/main/logout_bu.png
  src/main/resources/static/static_Image/common/main/logout_wh.png
  src/main/resources/static/static_Image/common/main/mainImage1.png
  src/main/resources/static/static_Image/common/main/mainImage2.png
  src/main/resources/static/static_Image/common/main/mainImage3.png
  src/main/resources/static/static_Image/common/main/mainReviewDogEx.png
  src/main/resources/static/static_Image/common/main/mypage_bk.png
  src/main/resources/static/static_Image/common/main/mypage_bl.png
  src/main/resources/static/static_Image/common/main/mypage_bu.png
  src/main/resources/static/static_Image/common/main/mypage_wh.png
  src/main/resources/static/static_Image/common/main/star_1.png
  src/main/resources/static/static_Image/member/add_user_bk.png
  src/main/resources/static/static_Image/member/add_user_bu.png
  src/main/resources/static/static_Image/member/add_user_wh.png
  src/main/resources/static/static_Image/member/admin_bk.png
  src/main/resources/static/static_Image/member/admin_bu.png
  src/main/resources/static/static_Image/member/admin_wh.png
  src/main/resources/static/static_Image/member/favicon.ico
  src/main/resources/static/static_Image/member/login_bk.png
  src/main/resources/static/static_Image/member/login_bu.png
  src/main/resources/static/static_Image/member/login_wh.png
  src/main/resources/static/static_Image/member/logout_bk.png
  src/main/resources/static/static_Image/member/logout_bu.png
  src/main/resources/static/static_Image/member/logout_wh.png
  src/main/resources/static/static_Image/member/mypage_bk.png
  src/main/resources/static/static_Image/member/mypage_bu.png
  src/main/resources/static/static_Image/member/mypage_wh.png
  src/main/resources/templates/common/footer.html
  src/main/resources/templates/common/header_black.html
  src/main/resources/templates/common/header_white.html
  src/main/resources/templates/main/main.html
  src/main/resources/templates/main/mainPage.html
Labels: Feature, HTML & CSS, FE

#45 chore / #5 / application 파일 이동
  src/main/java/com/mypet/petmily/PetmilyApplication.java
Labels: Fix, Setting

#47 Feature/#12/login
  build.gradle
  src/main/java/com/mypet/petmily/PetmilyApplication.java
  src/main/java/com/mypet/petmily/config/MessageConfig.java
  src/main/java/com/mypet/petmily/config/RedisConfig.java
  src/main/java/com/mypet/petmily/config/SpringSecurityConfiguration.java
  src/main/java/com/mypet/petmily/main/controller/MainController.java
  src/main/java/com/mypet/petmily/member/controller/MemberController.java
  src/main/java/com/mypet/petmily/member/dao/MemberMapper.java
  src/main/java/com/mypet/petmily/member/dto/MemberDTO.java
  src/main/java/com/mypet/petmily/member/service/AuthenticationService.java
  src/main/java/com/mypet/petmily/member/service/MemberService.java
  src/main/resources/application.yml
  src/main/resources/mappers/MemberMapper.xml
  src/main/resources/messages/messages_ko_KR.properties
  src/main/resources/static/css/member/style_.css
  src/main/resources/static/js/common/headerFooter.js
  src/main/resources/static/js/member/event.js
  src/main/resources/templates/main/main.html
  src/main/resources/templates/member/find_id-pwd.html
  src/main/resources/templates/member/login.html
  src/main/resources/templates/member/pet-profile-regist.html
Labels: Feature, HTML & CSS, FE, BE

#48 Feature/22 petsitter mypage
  build.gradle
  src/main/java/com/mypet/petmily/petSitter/controller/ExampleController.java
  src/main/java/com/mypet/petmily/petSitter/controller/PetSitterController.java
  src/main/java/com/mypet/petmily/petSitter/dao/ExampleMapper.java
  src/main/java/com/mypet/petmily/petSitter/dao/MypageMapper.java
  src/main/java/com/mypet/petmily/petSitter/dto/ExampleDTO.java
  src/main/java/com/mypet/petmily/petSitter/dto/PetsitterDTO.java
  src/main/java/com/mypet/petmily/petSitter/service/ExampleService.java
  src/main/java/com/mypet/petmily/petSitter/service/MypageService.java
  src/main/resources/application.yml
  src/main/resources/mappers/PetSitterMapper.xml
  src/main/resources/static/css/petSitter/account.css
  src/main/resources/static/css/petSitter/mypage.css
  src/main/resources/static/static_Image/petSitter/arrow.png
  src/main/resources/static/static_Image/petSitter/photo.png
  src/main/resources/templates/petSitter/account.html
  src/main/resources/templates/petSitter/mypage.html
Labels: Feature, HTML & CSS, FE

#49 feat/#22/ PetSitterMapper 수정
  src/main/resources/mappers/PetSitterMapper.xml
Labels: Fix

#50 Feature/#2 board setting
  petmily.eml
  src/main/java/com/mypet/petmily/PetmilyApplication.java
  src/main/java/com/mypet/petmily/board/CreatePagingTag.java
  src/main/java/com/mypet/petmily/board/controller/BoardController.java
  src/main/java/com/mypet/petmily/board/controller/ExampleController.java
  src/main/java/com/mypet/petmily/board/dao/BoardMapper.java
  src/main/java/com/mypet/petmily/board/dao/ExampleMapper.java
  src/main/java/com/mypet/petmily/board/dto/BoardDTO.java
  src/main/java/com/mypet/petmily/board/dto/ExampleDTO.java
  src/main/java/com/mypet/petmily/board/service/BoardService.java
  src/main/java/com/mypet/petmily/board/service/ExampleService.java
  src/main/java/com/mypet/petmily/member/controller/MemberController.java
  src/main/java/com/mypet/petmily/member/service/MemberService.java
  src/main/resources/application.yml
  src/main/resources/mappers/board/BoardMapper.xml
  src/main/resources/static/css/board/css.css
  src/main/resources/static/css/board/faq.css
  src/main/resources/static/css/board/list.css
  src/main/resources/static/css/board/media.css
  src/main/resources/static/css/board/style.css
  src/main/resources/static/static_Image/board/search.png
  src/main/resources/templates/board/notice/edit.html
  src/main/resources/templates/board/notice/list.html
  src/main/resources/templates/board/notice/view.html
  src/main/resources/templates/board/notice/write.html
  src/main/resources/templates/board/qna/edit.html
  src/main/resources/templates/board/qna/list.html
  src/main/resources/templates/board/qna/secrete.html
  src/main/resources/templates/board/qna/view.html
  src/main/resources/templates/board/qna/write.html
  src/test/petmily.test.eml
Labels: Feature, HTML & CSS, Setting, FE, BE

#51 Revert "Feature/#2 board setting"
  petmily.eml
  src/main/java/com/mypet/petmily/PetmilyApplication.java
  src/main/java/com/mypet/petmily/board/CreatePagingTag.java
  src/main/java/com/mypet/petmily/board/controller/BoardController.java
  src/main/java/com/mypet/petmily/board/controller/ExampleController.java
  src/main/java/com/mypet/petmily/board/dao/BoardMapper.java
  src/main/java/com/mypet/petmily/board/dao/ExampleMapper.java
  src/main/java/com/mypet/petmily/board/dto/BoardDTO.java
  src/main/java/com/mypet/petmily/board/dto/ExampleDTO.java
  src/main/java/com/mypet/petmily/board/service/BoardService.java
  src/main/java/com/mypet/petmily/board/service/ExampleService.java
  src/main/java/com/mypet/petmily/member/controller/MemberController.java
  src/main/java/com/mypet/petmily/member/service/MemberService.java
  src/main/resources/application.yml
  src/main/resources/mappers/board/BoardMapper.xml
  src/main/resources/static/css/board/css.css
  src/main/resources/static/css/board/faq.css
  src/main/resources/static/css/board/list.css
  src/main/resources/static/css/board/media.css
  src/main/resources/static/css/board/style.css
  src/main/resources/static/static_Image/board/search.png
  src/main/resources/templates/board/Example.html
  src/main/resources/templates/board/notice/edit.html
  src/main/resources/templates/board/notice/list.html
  src/main/resources/templates/board/notice/view.html
  src/main/resources/templates/board/notice/write.html
  src/main/resources/templates/board/qna/edit.html
  src/main/resources/templates/board/qna/list.html
  src/main/resources/templates/board/qna/view.html
  src/main/resources/templates/board/qna/write.html
  src/test/petmily.test.eml
Labels: Bug, Fix

#52 Feature/#6/pet sitter profile UI
  src/main/java/com/mypet/petmily/petSitter/controller/PetSitterProfileController.java
  src/main/resources/static/css/petSitter/petsitterProfile.css
  src/main/resources/static/js/petSitter/petSitterProfile.js
  src/main/resources/templates/petSitter/petSitterProfile.html
Labels: Feature, HTML & CSS, Setting, FE

#53 Feat/#3/admin UI avatar
  build.gradle
  src/main/java/com/mypet/petmily/admin/controller/CouplingController.java
  src/main/java/com/mypet/petmily/admin/controller/UserController.java
  src/main/java/com/mypet/petmily/admin/dao/UserDAO.java
  src/main/java/com/mypet/petmily/admin/dto/ExampleDTO.java
  src/main/java/com/mypet/petmily/admin/dto/UserDTO.java
  src/main/java/com/mypet/petmily/admin/service/UserService.java
  src/main/java/com/mypet/petmily/admin/service/UserServiceImpl.java
  src/main/resources/application.yml
  src/main/resources/static/css/admin/admin.css
  src/main/resources/static/js/admin/admin.js
  src/main/resources/templates/admin/Example.html
  src/main/resources/templates/admin/MailManagement/automail.html
  src/main/resources/templates/admin/member/applyform.html
  src/main/resources/templates/admin/member/board.html
  src/main/resources/templates/admin/member/comment.html
  src/main/resources/templates/admin/member/main-member.html
  src/main/resources/templates/admin/member/management.html
  src/main/resources/templates/admin/member/reservation.html
  src/main/resources/templates/admin/member/secession.html
  src/main/resources/templates/admin/statistics/atmosphere.html
  src/main/resources/templates/admin/statistics/complete.html
  src/main/resources/templates/admin/statistics/sales.html
Labels: Feature, HTML & CSS, Setting, FE, BE

#54 Feat/#2/NoticeQnaFaqUI
  src/main/java/com/mypet/petmily/board/controller/BoardController.java
  src/main/java/com/mypet/petmily/board/controller/ExampleController.java
  src/main/java/com/mypet/petmily/board/dao/BoardMapper.java
  src/main/java/com/mypet/petmily/board/dao/ExampleMapper.java
  src/main/java/com/mypet/petmily/board/dto/BoardDTO.java
  src/main/java/com/mypet/petmily/board/dto/ExampleDTO.java
  src/main/java/com/mypet/petmily/board/service/BoardService.java
  src/main/java/com/mypet/petmily/board/service/ExampleService.java
  src/main/resources/application.yml
  src/main/resources/mappers/BoardMapper.xml
  src/main/resources/static/css/board/css.css
  src/main/resources/static/css/board/faq.css
  src/main/resources/static/css/board/list.css
  src/main/resources/static/css/board/media.css
  src/main/resources/static/css/board/style.css
  src/main/resources/templates/board/Example.html
  src/main/resources/templates/board/notice/edit.html
  src/main/resources/templates/board/notice/list.html
  src/main/resources/templates/board/notice/view.html
  src/main/resources/templates/board/notice/write.html
Labels: Feature, HTML & CSS, FE, BE

#55 Feat/#31/update
  src/main/java/com/mypet/petmily/PetmilyApplication.java
  src/main/java/com/mypet/petmily/common/exception/member/MemberPasswordUpdateException.java
  src/main/java/com/mypet/petmily/common/exception/member/MemberRemoveException.java
  src/main/java/com/mypet/petmily/member/controller/MemberController.java
  src/main/java/com/mypet/petmily/member/dao/MemberMapper.java
  src/main/java/com/mypet/petmily/member/dto/MemberDTO.java
  src/main/java/com/mypet/petmily/member/service/MemberService.java
  src/main/resources/application.yml
  src/main/resources/mappers/MemberMapper.xml
  src/main/resources/messages/messages_ko_KR.properties
  src/main/resources/static/css/member/myInfo.css
  src/main/resources/static/css/member/mypage.css
  src/main/resources/static/css/member/regist.css
  src/main/resources/static/css/member/socialRegist.css
  src/main/resources/static/css/member/update.css
  src/main/resources/static/css/member/updatePassword.css
  src/main/resources/static/js/member/myInfo.js
  src/main/resources/static/js/member/mypage.js
  src/main/resources/static/js/member/regist.js
  src/main/resources/static/static_Image/member/target_img_name.png
  src/main/resources/templates/member/myInfo.html
  src/main/resources/templates/member/mypage.html
  src/main/resources/templates/member/regist.html
  src/main/resources/templates/member/socialRegist.html
  src/main/resources/templates/member/update.html
  src/main/resources/templates/member/updatePassword.html
Labels: Feature, HTML & CSS, FE, BE

#57 Feature/#6/pet sitter profile UI
  src/main/java/com/mypet/petmily/board/controller/BoardController.java
  src/main/resources/static/css/petSitter/fullCalendarMain.css
  src/main/resources/static/css/petSitter/petsitterProfile.css
  src/main/resources/static/js/petSitter/fullCalendarLocales-all.js
  src/main/resources/static/js/petSitter/fullCalendarLocales-all.min.js
  src/main/resources/static/js/petSitter/fullCalendarMain.js
  src/main/resources/static/js/petSitter/fullCalendarMain.min.js
  src/main/resources/static/js/petSitter/petSitterProfile.js
  src/main/resources/static/static_Image/petSitter/dog.png
  src/main/resources/static/static_Image/petSitter/dog_next.png
  src/main/resources/static/static_Image/petSitter/env_baby.png
  src/main/resources/static/static_Image/petSitter/env_count.png
  src/main/resources/static/static_Image/petSitter/env_dog.png
  src/main/resources/static/static_Image/petSitter/env_fence.png
  src/main/resources/static/static_Image/petSitter/env_home.png
  src/main/resources/static/static_Image/petSitter/env_smoke.png
  src/main/resources/static/static_Image/petSitter/petsitterPet.png
  src/main/resources/static/static_Image/petSitter/profile_img.png
  src/main/resources/static/static_Image/petSitter/profile_main.png
  src/main/resources/static/static_Image/petSitter/profile_sub1.png
  src/main/resources/static/static_Image/petSitter/profile_sub2.png
  src/main/resources/static/static_Image/petSitter/profile_sub3.png
  src/main/resources/static/static_Image/petSitter/profile_sub4.png
  src/main/resources/static/static_Image/petSitter/profile_sub5.png
  src/main/resources/static/static_Image/petSitter/profile_sub6.png
  src/main/resources/static/static_Image/petSitter/reviewProfile.png
  src/main/resources/static/static_Image/petSitter/star_1.png
  src/main/resources/static/static_Image/petSitter/watch.png
  src/main/resources/templates/main/mainPage.html
  src/main/resources/templates/petSitter/petSitterProfile.html
Labels: Feature, HTML & CSS, FE

#58 Feature/#13/find id pwd
  .gitignore
  src/main/java/com/mypet/petmily/member/controller/MemberController.java
  src/main/java/com/mypet/petmily/member/dao/MemberMapper.java
  src/main/java/com/mypet/petmily/member/dto/MailDTO.java
  src/main/java/com/mypet/petmily/member/dto/MemberDTO.java
  src/main/java/com/mypet/petmily/member/service/MemberService.java
  src/main/resources/mappers/MemberMapper.xml
  src/main/resources/static/css/member/style_.css
  src/main/resources/static/js/member/event.js
  src/main/resources/templates/member/find_id-pwd.html
  src/main/resources/templates/member/find_id.html
  src/main/resources/templates/member/find_id_result.html
  src/main/resources/templates/member/find_pwd.html
  src/main/resources/templates/member/find_pwd_result.html
  src/main/resources/templates/member/login.html
Labels: Feature, HTML & CSS, FE, BE

#59 fix/#4/Header&Footer 버그수정
  src/main/resources/static/css/common/headerFooter.css
  src/main/resources/templates/common/header_black.html
  src/main/resources/templates/common/header_white.html
Labels: Bug, Fix, HTML & CSS

#61 Feature/#38/reservation pay
  src/main/java/com/mypet/petmily/common/paging/Pagenation.java
  src/main/java/com/mypet/petmily/common/paging/SelectCriteria.java
  src/main/java/com/mypet/petmily/member/controller/MemberController.java
  src/main/java/com/mypet/petmily/member/dao/MemberMapper.java
  src/main/java/com/mypet/petmily/member/dto/MailDTO.java
  src/main/java/com/mypet/petmily/member/dto/MemberDTO.java
  src/main/java/com/mypet/petmily/member/dto/PetDTO.java
  src/main/java/com/mypet/petmily/member/service/MemberService.java
  src/main/java/com/mypet/petmily/reservation/controller/ExampleController.java
  src/main/java/com/mypet/petmily/reservation/dao/ExampleMapper.java
  src/main/java/com/mypet/petmily/reservation/dto/ExampleDTO.java
  src/main/java/com/mypet/petmily/reservation/service/ExampleService.java
  src/main/java/com/mypet/petmily/review/dto/ExampleDTO.java
  src/main/java/com/mypet/petmily/review/dto/ReviewDTO.java
  src/main/resources/mappers/MemberMapper.xml
  src/main/resources/static/css/member/style_.css
  src/main/resources/static/js/member/event.js
  src/main/resources/static/static_Image/member/petProfile.png
  src/main/resources/static/static_Image/member/petProfileTest1.png
  src/main/resources/static/static_Image/member/petProfileTest2.png
  src/main/resources/static/static_Image/member/petProfileTest3.png
  src/main/resources/static/static_Image/member/petProfileTest4.jpg
  src/main/resources/static/static_Image/member/petProfileTest5.jpg
  src/main/resources/static/static_Image/member/petProfileTest6.jpg
  src/main/resources/templates/member/login.html
  src/main/resources/templates/member/pet-profile-regist.html
  src/main/resources/templates/member/pet-profile-view.html
  src/main/resources/templates/member/reservation-history.html
  src/main/resources/templates/member/reservation-in-progress.html
  src/main/resources/templates/member/review-list.html
  src/main/resources/templates/member/review_write.html
Labels: FE

#62 Feature/#37/reservation details
  src/main/java/com/mypet/petmily/config/SpringSecurityConfiguration.java
  src/main/java/com/mypet/petmily/member/controller/MemberController.java
  src/main/resources/mappers/MemberMapper.xml
  src/main/resources/static/css/member/completedRegist.css
  src/main/resources/static/css/member/mainRegist.css
  src/main/resources/static/css/member/mypage.css
  src/main/resources/static/css/member/regist.css
  src/main/resources/static/css/member/update.css
  src/main/resources/static/js/common/headerFooter.js
  src/main/resources/static/js/member/mypage.js
  src/main/resources/static/js/member/regist.js
  src/main/resources/templates/common/header_black.html
  src/main/resources/templates/common/header_white.html
  src/main/resources/templates/member/completedRegist.html
  src/main/resources/templates/member/find_id.html
  src/main/resources/templates/member/login.html
  src/main/resources/templates/member/mainRegist.html
  src/main/resources/templates/member/mypage.html
  src/main/resources/templates/member/regist.html
  src/main/resources/templates/member/res_info.html
  src/main/resources/templates/member/update.html
Labels: Fix, HTML & CSS, FE

#63 Feature/#2/notice qna faq UI
  src/main/java/com/mypet/petmily/board/CreatePagingTag.java
  src/main/java/com/mypet/petmily/board/controller/BoardController.java
  src/main/java/com/mypet/petmily/board/dao/BoardMapper.java
  src/main/java/com/mypet/petmily/board/dto/BoardDTO.java
  src/main/java/com/mypet/petmily/board/service/BoardService.java
  src/main/java/com/mypet/petmily/main/controller/MainController.java
  src/main/resources/mappers/BoardMapper.xml
  src/main/resources/static/js/common/headerFooter.js
  src/main/resources/templates/board/faq.html
  src/main/resources/templates/board/faq/list.html
  src/main/resources/templates/board/notice/list.html
  src/main/resources/templates/board/notice/view.html
  src/main/resources/templates/board/notice/write.html
  src/main/resources/templates/board/policy.html
  src/main/resources/templates/board/qna/list.html
  src/main/resources/templates/board/qna/view.html
  src/main/resources/templates/board/qna/write.html
  src/main/resources/templates/board/safe.html
  src/main/resources/templates/board/service.html
  src/main/resources/templates/board/terms.html
Labels: HTML & CSS, FE

#65 feat/#35/예약조회페이지, 회원가입 오류 수정
  src/main/java/com/mypet/petmily/member/controller/MemberController.java
  src/main/java/com/mypet/petmily/member/dao/MemberMapper.java
  src/main/java/com/mypet/petmily/member/service/MemberService.java
  src/main/resources/mappers/MemberMapper.xml
  src/main/resources/templates/member/reservationList.html
Labels: BE

#66 중간 커밋
  src/main/java/com/mypet/petmily/member/controller/MemberController.java
  src/main/resources/mappers/MemberMapper.xml
Labels: FE

#68 Feat/#11/update
  src/main/java/com/mypet/petmily/member/controller/MemberController.java
  src/main/java/com/mypet/petmily/member/dao/MemberMapper.java
  src/main/java/com/mypet/petmily/member/service/MemberService.java
  src/main/resources/mappers/MemberMapper.xml
  src/main/resources/static/css/member/completedRegist.css
  src/main/resources/static/css/member/mainRegist.css
  src/main/resources/static/css/member/regist.css
  src/main/resources/static/js/member/regist.js
  src/main/resources/templates/member/mainRegist.html
  src/main/resources/templates/member/regist.html
Labels: Fix, Feature, HTML & CSS, FE

#70 feature/#30/petSitterRegist
  src/main/java/com/mypet/petmily/common/exception/petSitter/PetSitterRegistException.java
  src/main/java/com/mypet/petmily/petSitter/controller/PetSitterController.java
  src/main/java/com/mypet/petmily/petSitter/service/PetSitterService.java
  src/main/resources/sqlScript/04_insert문_ver1.7.txt
  src/main/resources/static/js/common/headerFooter.js
  src/main/resources/static/js/petSitter/petSitterProfile.js
  src/main/resources/templates/common/header_black.html
  src/main/resources/templates/petSitter/petSitterRegist.html
Labels: Feature, HTML & CSS, FE, BE

#72 Feature/#30/pet sitter regist
  src/main/java/com/mypet/petmily/petSitter/controller/PetSitterController2.java
  src/main/java/com/mypet/petmily/petSitter/dao/PetSitterMapper.java
  src/main/java/com/mypet/petmily/petSitter/dao/PetSitterMapper2.java
  src/main/java/com/mypet/petmily/petSitter/dto/PetSitterDTO2.java
  src/main/java/com/mypet/petmily/petSitter/dto/ReservationDTO.java
  src/main/java/com/mypet/petmily/petSitter/service/PetSitterService2.java
  src/main/java/com/mypet/petmily/review/dto/ReviewDTO.java
  src/main/resources/mappers/PetSitterMapper2.xml
  src/main/resources/templates/common/header_white.html
  src/main/resources/templates/petSitter/petSitterRegist.html
Labels: Fix, Setting

#73 Feature/#30/pet sitter regist
  src/main/java/com/mypet/petmily/member/controller/MemberController.java
  src/main/java/com/mypet/petmily/member/dao/MemberMapper.java
  src/main/java/com/mypet/petmily/member/service/MemberService.java
  src/main/java/com/mypet/petmily/petSitter/controller/PetSitterController.java
  src/main/java/com/mypet/petmily/petSitter/dao/PetSitterMapper.java
  src/main/java/com/mypet/petmily/petSitter/dao/PetSitterMapper2.java
  src/main/java/com/mypet/petmily/petSitter/dto/PetSitterDTO.java
  src/main/java/com/mypet/petmily/petSitter/service/PetSitterService.java
  src/main/java/com/mypet/petmily/petSitter/service/PetSitterService2.java
  src/main/java/com/mypet/petmily/petSitterNew/controller/NewPetSitterController.java
  src/main/java/com/mypet/petmily/petSitterNew/dao/NewPetSitterMapper.java
  src/main/java/com/mypet/petmily/petSitterNew/dto/CareerDTO.java
  src/main/java/com/mypet/petmily/petSitterNew/dto/NewPetSitterDTO.java
  src/main/java/com/mypet/petmily/petSitterNew/dto/PetJsonMemberDTO.java
  src/main/java/com/mypet/petmily/petSitterNew/dto/PetTagDTO.java
  src/main/java/com/mypet/petmily/petSitterNew/dto/ReservationDTO.java
  src/main/java/com/mypet/petmily/petSitterNew/dto/SitterScheduleDTO.java
  src/main/java/com/mypet/petmily/petSitterNew/service/NewPetSitterService.java
  src/main/java/com/mypet/petmily/review/dto/ReviewDTO.java
  src/main/resources/mappers/MemberMapper.xml
  src/main/resources/mappers/PetSitterMapper.xml
  src/main/resources/mappers/new/NewPetSitterMapper.xml
  src/main/resources/static/js/common/headerFooter.js
  src/main/resources/static/js/petSitter/petSitterProfile.js
  src/main/resources/templates/petSitterNew/petSitterProfile.html
  src/main/resources/templates/petSitterNew/petSitterRegist.html
  src/main/resources/templates/petSitterNew/resRegistSuccess.html
Labels: Fix, Setting

#74 Feature/#27/petsitter search
  src/main/java/com/mypet/petmily/petSitter/controller/PetSitterController.java
  src/main/java/com/mypet/petmily/petSitter/dao/MypageMapper.java
  src/main/java/com/mypet/petmily/petSitter/dao/PetSitterMapper.java
  src/main/java/com/mypet/petmily/petSitter/dto/Pagenation/Pagenation.java
  src/main/java/com/mypet/petmily/petSitter/dto/PetSitterDTO.java
  src/main/java/com/mypet/petmily/petSitter/dto/ReviewDTO.java
  src/main/java/com/mypet/petmily/petSitter/dto/SelectCriteria/SelectCriteria.java
  src/main/java/com/mypet/petmily/petSitter/service/PetSitterService.java
  src/main/resources/application.yml
  src/main/resources/mappers/PetSitterMapper.xml
  src/main/resources/static/css/petSitter/reservationList.css
  src/main/resources/static/css/petSitter/searchPage.css
  src/main/resources/static/js/petSitter/reservationList.js
  src/main/resources/templates/petSitter/reservationList.html
  src/main/resources/templates/petSitter/searchPage.html
Labels: Feature, FE, BE

#75 Feature/#32/pet profile
  src/main/java/com/mypet/petmily/common/exception/member/PetRemoveException.java
  src/main/java/com/mypet/petmily/member/controller/MemberController.java
  src/main/java/com/mypet/petmily/member/dao/MemberMapper.java
  src/main/java/com/mypet/petmily/member/service/MemberService.java
  src/main/resources/mappers/MemberMapper.xml
  src/main/resources/messages/messages_ko_KR.properties
  src/main/resources/templates/member/mypage.html
  src/main/resources/templates/member/pet-profile-regist.html
  src/main/resources/templates/member/pet-profile-update.html
  src/main/resources/templates/member/pet-profile-view.html
Labels: BE

#79 Feat/#37/reservationhistory
  src/main/java/com/mypet/petmily/payment/controller/PaymentController.java
  src/main/java/com/mypet/petmily/payment/dto/ReservationHistoryDTO.java
  src/main/resources/mappers/PaymentMapper.xml
  src/main/resources/templates/member/reservationList.html
Labels: BE

#84 Feature/#34/review
  src/main/java/com/mypet/petmily/common/paging/Pagination.java
  src/main/java/com/mypet/petmily/config/SpringSecurityConfiguration.java
  src/main/java/com/mypet/petmily/main/controller/MainController.java
  src/main/java/com/mypet/petmily/member/controller/MemberController.java
  src/main/java/com/mypet/petmily/member/dao/MemberMapper.java
  src/main/java/com/mypet/petmily/member/dto/MemberDTO.java
  src/main/java/com/mypet/petmily/member/dto/PetDTO.java
  src/main/java/com/mypet/petmily/member/service/AuthenticationService.java
  src/main/java/com/mypet/petmily/member/service/MemberService.java
  src/main/java/com/mypet/petmily/payment/dto/ReservationHistoryDTO.java
  src/main/java/com/mypet/petmily/review/controller/ExampleController.java
  src/main/java/com/mypet/petmily/review/controller/ReviewController.java
  src/main/java/com/mypet/petmily/review/dao/ExampleMapper.java
  src/main/java/com/mypet/petmily/review/dao/ReviewMapper.java
  src/main/java/com/mypet/petmily/review/dto/ReservationInfoDTO.java
  src/main/java/com/mypet/petmily/review/dto/ReviewDTO.java
  src/main/java/com/mypet/petmily/review/dto/ReviewSitterInfoDTO.java
  src/main/java/com/mypet/petmily/review/service/ExampleService.java
  src/main/java/com/mypet/petmily/review/service/ReviewService.java
  src/main/resources/mappers/MemberMapper.xml
  src/main/resources/mappers/PaymentMapper.xml
  src/main/resources/mappers/ReviewMapper.xml
  src/main/resources/static/css/member/mypage.css
  src/main/resources/static/css/member/style_.css
  src/main/resources/templates/member/mypage.html
  src/main/resources/templates/member/pet-profile-regist.html
  src/main/resources/templates/member/pet-profile-update.html
  src/main/resources/templates/member/reservationList.html
  src/main/resources/templates/member/review-list.html
  src/main/resources/templates/member/review-view.html
  src/main/resources/templates/member/review-write.html
Labels: Feature, FE, BE

#85 Feat/#37/reservation detail
  src/main/java/com/mypet/petmily/common/exception/member/ReservationListException.java
  src/main/java/com/mypet/petmily/common/exception/member/reservationDetailException.java
  src/main/java/com/mypet/petmily/payment/controller/PaymentController.java
  src/main/java/com/mypet/petmily/payment/dao/PaymentMapper.java
  src/main/java/com/mypet/petmily/payment/service/PaymentService.java
  src/main/resources/mappers/PaymentMapper.xml
  src/main/resources/messages/messages_ko_KR.properties
  src/main/resources/static/css/member/reservationDetail.css
  src/main/resources/static/css/member/style_.css
  src/main/resources/static/js/member/regist.js
  src/main/resources/static/js/member/reservationList.js
  src/main/resources/templates/member/pet-profile-list.html
  src/main/resources/templates/member/reservationDetail.html
  src/main/resources/templates/member/reservationList.html
Labels: FE

#86 Feature/#27/petsitter search
  src/main/java/com/mypet/petmily/main/controller/MainController.java
  src/main/java/com/mypet/petmily/main/dao/MainMapper.java
  src/main/java/com/mypet/petmily/main/service/MainService.java
  src/main/java/com/mypet/petmily/petSitter/controller/PetSitterController.java
  src/main/java/com/mypet/petmily/petSitter/dao/PetSitterMapper.java
  src/main/java/com/mypet/petmily/petSitter/dto/Pagenation.java
  src/main/java/com/mypet/petmily/petSitter/dto/PetSitterDTO.java
  src/main/java/com/mypet/petmily/petSitter/dto/SelectCriteria.java
  src/main/java/com/mypet/petmily/petSitter/service/MypageService.java
  src/main/java/com/mypet/petmily/petSitter/service/PetSitterService.java
  src/main/resources/mappers/PetSitterMapper.xml
  src/main/resources/static/css/petSitter/searchPage.css
  src/main/resources/static/js/common/headerFooter.js
  src/main/resources/static/static_Image/petSitter/photo1.png
  src/main/resources/static/static_Image/petSitter/profileDog.png
  src/main/resources/static/static_Image/petSitter/star-icon.png
  src/main/resources/templates/main/mainPage.html
  src/main/resources/templates/petSitter/mypage.html
  src/main/resources/templates/petSitter/searchPage.html
Labels: Feature, FE, BE

#89 feat/#27/ DB수정
  src/main/java/com/mypet/petmily/petSitter/dto/Pagenation/Pagenation.java
  src/main/java/com/mypet/petmily/petSitter/pagnation/Pagenation.java
  src/main/java/com/mypet/petmily/petSitter/service/PetSitterService.java
  src/main/resources/application.yml
  src/main/resources/mappers/PetSitterMapper.xml
Labels: Feature, BE

#90 Feature/#34/review
  src/main/java/com/mypet/petmily/fileUpload/dao/FileUploadMapper.java
  src/main/java/com/mypet/petmily/member/controller/MemberController.java
  src/main/java/com/mypet/petmily/member/dao/MemberMapper.java
  src/main/java/com/mypet/petmily/member/dto/PetDTO.java
  src/main/java/com/mypet/petmily/member/service/MemberService.java
  src/main/java/com/mypet/petmily/review/dto/ReviewDTO.java
  src/main/resources/application.yml
  src/main/resources/mappers/FileUploadMapper.xml
  src/main/resources/mappers/MemberMapper.xml
  src/main/resources/mappers/ReviewMapper.xml
  src/main/resources/static/css/member/style_.css
  src/main/resources/templates/member/pet-profile-list.html
  src/main/resources/templates/member/pet-profile-regist.html
  src/main/resources/templates/member/pet-profile-update.html
  src/main/resources/templates/member/pet-profile-view.html
  src/main/resources/templates/member/reservationList.html
  src/main/resources/templates/member/review-write.html
  src/main/resources/upload/original/0f40ef78-ba0f-44dd-a05d-66943f68636a.jpg
  src/main/resources/upload/original/1fb22486-e86d-46b0-bd48-4a1f12d7b990.png
  src/main/resources/upload/original/3cee70be-b3f5-43c0-aa44-534cb3bc35cc.jpg
  src/main/resources/upload/original/63f8e35c-34d1-4954-9b48-e8a0b36ed2ca.jpg
  src/main/resources/upload/original/77447efa-9aaa-46a4-aa48-8d144448dde8.jpg
  src/main/resources/upload/original/88396554-6ef2-472d-8818-f5cbccb7298a.jpg
  src/main/resources/upload/original/baf96c0e-0bad-4b24-938b-4a9eac8b67df.jpg
  src/main/resources/upload/original/c60bd38a-19fe-4a87-887c-13c5b47a649c.png
  src/main/resources/upload/original/d0f17f00-4087-484d-85e0-ef9f8ad50191.jpg
  src/main/resources/upload/original/e19c1af7-2759-4bfb-a0b8-6357a4112463.jpg
  src/main/resources/upload/original/f26f0d69-bec1-48cd-a385-1b28aa008fb5.jpg
  src/main/resources/upload/original/fb34106c-13d9-4330-bd48-83defbfa7493.jpg
  src/main/resources/upload/original/fce104df-bd80-4d0e-8175-e22c71b71a02.jpg
  src/main/resources/upload/thumbnail/thumbnail_0f40ef78-ba0f-44dd-a05d-66943f68636a.jpg
  src/main/resources/upload/thumbnail/thumbnail_baf96c0e-0bad-4b24-938b-4a9eac8b67df.jpg
  src/main/resources/upload/thumbnail/thumbnail_c60bd38a-19fe-4a87-887c-13c5b47a649c.png
  src/main/resources/upload/thumbnail/thumbnail_f26f0d69-bec1-48cd-a385-1b28aa008fb5.jpg
Labels: Fix, FE, BE

#92 Feature/#32/pet profile
  src/main/java/com/mypet/petmily/member/controller/MemberController.java
  src/main/resources/mappers/MemberMapper.xml
  src/main/resources/static/css/member/mypage.css
  src/main/resources/templates/member/mypage.html
  src/main/resources/templates/member/pet-profile-list.html
Labels: Feature, BE

#93 feat/#27/css수정
  src/main/java/com/mypet/petmily/member/controller/MemberController.java
  src/main/java/com/mypet/petmily/petSitter/controller/PetSitterController.java
  src/main/java/com/mypet/petmily/petSitter/dao/PetSitterMapper.java
  src/main/java/com/mypet/petmily/petSitter/service/MypageService.java
  src/main/resources/mappers/PetSitterMapper.xml
  src/main/resources/static/css/petSitter/searchPage.css
  src/main/resources/static/static_Image/petSitter/star-icon.png
  src/main/resources/templates/member/mypage.html
  src/main/resources/templates/petSitter/mypage.html
  src/main/resources/templates/petSitter/searchPage.html
Labels: FE

#96 Feature/#6/pet sitter profile
  src/main/java/com/mypet/petmily/main/controller/MainController.java
  src/main/java/com/mypet/petmily/main/dao/MainMapper.java
  src/main/java/com/mypet/petmily/main/service/MainService.java
  src/main/java/com/mypet/petmily/petSitterNew/dao/NewPetSitterMapper.java
  src/main/java/com/mypet/petmily/petSitterNew/dto/NewPetSitterDTO.java
  src/main/java/com/mypet/petmily/petSitterNew/dto/SitterReviewDTO.java
  src/main/java/com/mypet/petmily/petSitterNew/service/NewPetSitterService.java
  src/main/resources/mappers/MainMapper.xml
  src/main/resources/mappers/PetSitterMapper.xml
  src/main/resources/mappers/new/NewPetSitterMapper.xml
Labels: Bug, Fix

#97 feature/#6/petSitterProfile 메인 리뷰 조회 구현
  src/main/resources/mappers/PetSitterMapper.xml
Labels: Bug, Fix

#98 Feature/#21/이용방법페이지 구현
  src/main/java/com/mypet/petmily/board/controller/BoardController.java
  src/main/java/com/mypet/petmily/board/dto/BoardDTO.java
  src/main/java/com/mypet/petmily/board/service/BoardService.java
  src/main/resources/application.yml
  src/main/resources/static/css/board/usingprocess.css
  src/main/resources/static/static_Image/board/날짜선택.png
  src/main/resources/static/static_Image/board/마이페이지.png
  src/main/resources/static/static_Image/board/이용후기.png
  src/main/resources/static/static_Image/board/펫시터 정보확인.png
  src/main/resources/static/static_Image/board/펫시터지원.png
  src/main/resources/static/static_Image/board/펫시터찾기.png
  src/main/resources/templates/board/usingprocess.html
Labels: Fix, Feature, HTML & CSS, FE

#99 feature/#6/petSitterProfile 메인 리뷰 조회 구현
  src/main/resources/static/css/main/mainPage.css
  src/main/resources/static/css/petSitterNew/petsitterProfile.css
  src/main/resources/static/static_Image/common/main/mainReview0.jpg
  src/main/resources/static/static_Image/common/main/mainReview1.jpg
  src/main/resources/static/static_Image/common/main/mainReview2.jpg
  src/main/resources/templates/main/mainPage.html
  src/main/resources/templates/petSitterNew/petSitterProfile.html
Labels: Feature, FE, BE

#100 Feature/#21/문의하기 버튼연결
  src/main/resources/static/js/petSitterNew/petSitterProfile.js
Labels: FE, BE

#101 Feature/#6/pet sitter profile
  src/main/resources/static/js/petSitterNew/petSitterProfile.js
  src/main/resources/static/static_Image/petSitter/petTestImg.jpg
  src/main/resources/templates/petSitterNew/petSitterProfile.html
Labels: Bug, Fix

#105 Feat/#37/reservation detail
  src/main/java/com/mypet/petmily/config/SpringSecurityConfiguration.java
  src/main/java/com/mypet/petmily/fileUpload/dao/FileUploadMapper.java
  src/main/java/com/mypet/petmily/member/controller/MemberController.java
  src/main/java/com/mypet/petmily/member/dao/MemberMapper.java
  src/main/java/com/mypet/petmily/member/dto/MemberDTO.java
  src/main/java/com/mypet/petmily/member/service/MemberService.java
  src/main/java/com/mypet/petmily/payment/controller/PaymentController.java
  src/main/java/com/mypet/petmily/payment/dao/PaymentMapper.java
  src/main/java/com/mypet/petmily/payment/dto/PaymentDTO.java
  src/main/java/com/mypet/petmily/payment/dto/ProgressReserveDTO.java
  src/main/java/com/mypet/petmily/payment/service/PaymentService.java
  src/main/resources/mappers/FileUploadMapper.xml
  src/main/resources/mappers/MemberMapper.xml
  src/main/resources/mappers/PaymentMapper.xml
  src/main/resources/static/css/member/reservationDetail.css
  src/main/resources/static/css/member/sidebar.css
  src/main/resources/static/css/member/style_.css
  src/main/resources/static/css/member/update.css
  src/main/resources/templates/member/reservationDetail.html
  src/main/resources/templates/member/reservationList.html
  src/main/resources/templates/member/review-list.html
  src/main/resources/templates/member/sidebar.html
  src/main/resources/templates/member/update.html
Labels: Feature, HTML & CSS, FE, BE

#107 Feature/#27/petsitter search
  src/main/java/com/mypet/petmily/member/controller/MemberController.java
  src/main/java/com/mypet/petmily/petSitter/controller/PetSitterController.java
  src/main/java/com/mypet/petmily/petSitter/dao/PetSitterMapper.java
  src/main/java/com/mypet/petmily/petSitter/service/MypageService.java
  src/main/java/com/mypet/petmily/petSitter/service/PetSitterService.java
  src/main/resources/application.yml
  src/main/resources/mappers/PetSitterMapper.xml
  src/main/resources/static/css/petSitter/account.css
  src/main/resources/static/css/petSitter/mypage.css
  src/main/resources/static/css/petSitter/searchPage.css
  src/main/resources/static/static_Image/petSitter/petsitter-image.png
  src/main/resources/static/static_Image/petSitter/photo1.png
  src/main/resources/templates/member/mypage.html
  src/main/resources/templates/petSitter/account.html
  src/main/resources/templates/petSitter/mypage.html
  src/main/resources/templates/petSitter/searchPage.html
Labels: Feature, FE

#108 Feature/#27/petsitter search
  src/main/java/com/mypet/petmily/petSitter/controller/PetSitterController.java
  src/main/java/com/mypet/petmily/petSitter/dao/PetSitterMapper.java
  src/main/java/com/mypet/petmily/petSitter/service/MypageService.java
  src/main/resources/mappers/PetSitterMapper.xml
  src/main/resources/static/css/petSitter/searchPage.css
  src/main/resources/templates/member/mypage.html
Labels: Feature, FE

#111 Feature/#6/pet sitter profile
  README.md
  src/main/resources/sqlScript/04_insert문_ver2.7.sql
Labels: Docs

#112 버그수정
  src/main/resources/static/js/petSitterNew/petSitterProfile.js
  src/main/resources/static/js/petSitterNew/petSitterRegist.js
  src/main/resources/templates/petSitterNew/petSitterProfile.html
Labels: Bug, Fix
